# ~/.config/databroker/mongodb_config.yml

description: 'heavyweight shared database'
metadatastore:
   module: 'databroker.headersource.mongo'
   class: 'MDS'
   config:
       host: 'mongo'
       port: 27017
       database: 'metadatastore-production-v1'
       timezone: 'US/Central'
assets:
   module: 'databroker.assets.mongo'
   class: 'Registry'
   config:
       host: 'mongo'
       port: 27017
       database: 'filestore-production-v1'